# Sets default memory used for gradle commands. Can be overridden by user or command line properties.
org.gradle.jvmargs=-Xmx2G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true

#read more on this at https://forge.gemwire.uk/wiki/mappings/
# Minecraft / Forge versions
# The Minecraft version must agree with the Forge version to get a valid artifact
minecraft_version=1.20.1
# The Minecraft version range can use any release version of Minecraft as bounds.
minecraft_version_range=[1.20.1]
# Forge version — see https://files.minecraftforge.net/net/minecraftforge/forge/index_1.20.1.html
forge_version=47.4.5
# Forge version range for the mods.toml forge dependency
forge_version_range=[47,)
# The loader version range can only use the major version of FML as bounds
loader_version_range=[41,)

## Mod Properties

# The unique mod identifier for the mod. Must be lowercase in English locale. Must fit the regex [a-z][a-z0-9_]{1,63}
# Must match the String constant located in the main mod class annotated with @Mod.
mod_id=protectionengineering
# The human-readable display name for the mod.
mod_name=Protection Engineering
# The license of the mod. Review your options at https://choosealicense.com/. All Rights Reserved is the default.
mod_license=MIT
# The mod version. See https://semver.org/
mod_version=1.6.0
# The group ID for the mod. It is only important when publishing as an artifact to a Maven repository.
# This should match the base package used for the mod sources.
mod_group_id=com.chemiofitor.protection_engineering


# Mod Dependencies
create_version=6.0.8-291
create_version_range=[6.0.0,)
ponder_version=1.0.92
flywheel_version=1.0.6-280
registrate_version=MC1.20-1.3.11
iron_spells_version=1.20.1-3.16.2
playeranimator_version=1.0.2-rc1+1.20-forge
curios_version=5.14.1+1.20.1
geckolib_version=4.8.4
irons_lib_version=1.20.1-2.1.0
mixinextras_version=0.3.6
